### ISSUE TITLE
SyntaxError: Unexpected token :

### ISSUE THREAD

**Issue by mvastola** [peerigon/modernizr-loader#41] opened 2017-09-16 18:03 UTC
So I'm getting a weird error, and I'm hoping someone can help me out. I'm a bit new to Webpack -- this is a rails app -- (though I'm a fairly advanced coder) so I could be doing something dumb.

The error is as follows
```
ERROR in ./app/javascript/modernizrrc.json
Module build failed: [PRIVATE]/app/javascript/modernizrrc.json:2
  "classPrefix": "",
               ^

SyntaxError: Unexpected token :
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.exec ([PRIVATE]/node_modules/webpack/lib/NormalModule.js:129:12)
    at Object.module.exports ([PRIVATE]/node_modules/modernizr-loader/index.js:24:26)
 @ ./app/javascript/packs/coming_soon.js 4:0-44
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/coming_soon.js
```

This makes no sense though, because (to my reading) this is a parser error regarding the the JSON config file, but I actually obtained the file directly from the `Modernizr` GitHub repo by running 
```
curl https://raw.githubusercontent.com/Modernizr/Modernizr/v3.5.0/lib/config-all.json > modernizrrc.json
```

For what it's worth, here's the config I'm using for my webpacker environment setup:
```
const path = require('path');

module.exports = {
  module: {
    rules: [
      {
        test: /\.?modernizrrc(\.js(on)?)?$/,
        use: [ 'modernizr-loader' ]
      }
    ]
  },
  resolve: {
    alias: {
      'modernizr$': path.resolve(__dirname, "../../../app/javascript/modernizrrc.json")
    }
  }
}
```

Any ideas?

**Comment by mvastola** [comment] 2017-09-16 18:08
Okay, I'm totally missing something here, because I just replaced the JSON file with `{}` and now I get the following error:
```
ERROR in ./app/javascript/modernizrrc.json
Module build failed: SyntaxError: Unexpected token ; in JSON at position 0
    at Object.parse (native)
    at Object.module.exports ([PRIVATE]/node_modules/json-loader/index.js:4:49)
 @ ./app/javascript/packs/coming_soon.js 4:0-29
 @ multi (webpack)-dev-server/client?http://localhost:3035 ./app/javascript/packs/coming_soon.js
```

**Comment by Tailzip** [comment] 2017-09-18 15:15
Same issue here!

**Comment by flootr** [comment] 2017-09-18 17:49
Thanks for reporting this issue. Unfortunately I'm not able to check this out before next Tuesday. Hope this works out for you both. @mvastola if you want to set up an example repository which reproduces this error this would be 👌

**Comment by mvastola** [comment] 2017-09-18 18:26
Done. 
See https://github.com/mvastola/modernizr-loader-issue-41/tree/issue1
FWIW, you don't really even need to check out a repo. Just run the following in an empty directory:

- `rails new  . --webpack` (Have the latest rails 5.0.x or 5.1.x installed first)
- `yarn add json-loader modernizr modernizr-loader`
- `curl https://raw.githubusercontent.com/Modernizr/Modernizr/v3.5.0/lib/config-all.json > app/javascript/modernizrrc.json`
- `echo 'import "json-loader!modernizr-loader!../modernizrrc.json"' > app/javascript/packs/application.js`
- `./bin/webpack-dev-server`

**Comment by RobinSiep** [comment] 2017-09-19 13:20
Having the same issue sadly.

**Comment by jnleonard3** [comment] 2017-09-27 15:51
For anyone who encounters this, which I did after I upgraded to Webpack 3, the fix was to add the json loader to the loader definition:
```
rules: [
  {
    test: /\.modernizrrc$/,
    loader: 'modernizr-loader!json-loader'
  }
]
```

**Comment by mvastola** [comment] 2017-09-27 16:40
Hrm. I thought I had tried this previously with a plain `.js` file and encountered a similar error. (Also, given #40, I assumed this wasn't necessary in any case.) 

Regardless, I just tried this again (using a plain javascript file -- containing the json file contents prefixed with `module.exports = `) and got a bit further, but I'm still having an error.  Please see https://github.com/mvastola/modernizr-loader-issue-41/tree/issue2 for what's going on. Basically, the script is working (the CSS classes are added) except for the fact that `window.Modernizr` isn't set/exported. The `README.md` has instructions for reproducing.

I'm going to see if I can narrow down what the JSON problem is separately.

**Comment by mvastola** [comment] 2017-09-27 16:46
Okay. Well the original compile error is fixed. I had put `import "json-loader!modernizr-loader!../modernizrrc.json"` but the order of the loaders apparently needed to be swapped (and `json-loader` *was* required -- #40 is incorrect and should be closed). This just leaves the issue from the previous comment.

**Comment by mvastola** [comment] 2017-10-18 01:14
@flootr, any chance you've been able to look at this?

**Comment by AntiFish03** [comment] 2017-10-24 06:35
To avoid the me too... (Although I must say I am having the issue as well on a Rails 5.1.4 project with webpacker, and webpack 3).  I have a webpack 1 project that its working perfectly with the same version of `modernizr`, `modernizr-loader`, and a similar `.modernizrrc.json`

~Also while changing over to use `.modernizrrc.js` seems to work as webpack builds, I am not getting classes on the dom and the tests like `Modernizr.fetch` are coming back `undefined`, in a browser I know supports fetch.~

Edit NVM that was my fault.  I messed up the `feature-detects` array... so I am in the same boat.   For now I don't need `Modernizr` available in the window anyways I can import the same object whenever I need to test something.

**Comment by mvastola** [comment] 2017-10-24 22:24
@AntiFish03, yeah. I originally triggered this issue in a rails app, but I was able to isolate it in https://github.com/mvastola/modernizr-loader-issue-41/tree/issue2 and duplicate the issue without rails. Maybe it has to do with the version of `webpack`? My example uses semver `^3.5.5`. I should actually try to clean it up a bit to see if I can get closer to the core issue.

**Comment by mvastola** [comment] 2017-10-24 23:10
Ok, I just pushed a few commits to https://github.com/mvastola/modernizr-loader-issue-41/tree/issue2 to vastly reduce the yarn modules it uses. Now there's only `webpack`, `modernizr` and `modernizr-loader` and the same issue occurs.

I tried downgrading as much as I could, setting the following in `package.json` and the error persisted:
```javascript
{
    "modernizr": "~3.1.0",
    "modernizr-loader": "^1.0.1",
    "webpack": "^2.0.0"
  }
```

I would have liked to try `webpack@^1.0.0` (as @AntiFish03 claims it worked on there) but version 1 doesn't seem to parse `import` directives as far as I can tell, and I'm not sure how to get around that.

**Comment by flootr** [comment] 2017-10-25 12:20
@mvastola I'm sorry to not keep up with this issue, hope to find some time towards the weekend. Maybe also @jhnns can provide some pointers.

**Comment by jhnns** [comment] 2017-10-26 17:17
@mvastola Have you tried to use it as described in the README?

```js
import Modernizr from './modernizrrc.js';
// or if you don't want to configure it in your webpack.config.js
// but I don't recommend this:
import Modernizr from "!modernizr-loader!./modernizrrc.js"

if (!Modernizr.promises) {
    // ...
}
```

modernizr will not expose itself to the `window` object if loaded as a module (in contrast to just including a `<script>` tag). After all, that's why you want to use a module bundler like webpack: to avoid the global namespace and its conflicts.

Since the original issue has been resolved (json-loader was missing) and the described behavior is intended (not present on the `window` object), I'm closing this issue.

**Closed as completed by jhnns** 2017-10-26 17:17 UTC

**Comment by mvastola** [comment] 2017-10-26 18:37
@jhnns Ahh. Ok. Shouldn't it be at least optional to expose to `Modernizr` in the `window` object though? I mean, there's more than one reason people use `webpack`..

In my case I'm using it because I'm using it to manage my asset pipeline in a rails app, and it would seem silly to need to have a separate `<script>` tag (or some other workaround like `window.Modernizr = Modernizr` to expose it). A simple use case for needing to do this is if I have an ajax script that depends on it.

**Comment by jhnns** [comment] 2017-10-27 14:49
If you have a module system, it's best practice not to clutter the global object anymore. I don't think that the modernizr-loader should do that. If you want to have it on the `window` object, just add it explicitly 😁
You can also use the script-loader which can be used if you just want to include something in the bundle, without using a module system.

**Comment by mvastola** [comment] 2017-10-27 22:30
Yeah, I get what you're saying. ~~Having to do it explicitly just seems.. clunky to me for some reason. Oh well, I'll live.~~ :-) Thanks a lot for looking into this anyhow!

**Comment by mvastola** [comment] 2017-10-27 23:47
**Update:** Retract that last bit about the clunkiness. Apparently I'm just too much of a n00b at `webpack` (apologies). For anyone else running into this see https://webpack.js.org/configuration/externals/.
Crisis averted. :-)
